# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    # Apuntamos a los archivos físicos dentro del contenedor
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'

    # Usamos la variable de entorno para la contraseña
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
        cookie:
            enabled: true
            name:    BEARER
