# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_PRIVATE_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'

    # Cambiado a pass_phrase con guion bajo como lo pide tu versión del bundle
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
        cookie:
            enabled: true
            name:    BEARER
