# Rutas manuales primero
app_demo_modulo:
    path: /vistas/demo/{id}
    controller: App\Controller\DemoController::demo

app_dashboard:
    path: /
    controller: App\Controller\DashboardController::index

api_login_check:
    path: /api/login_check
    methods: [POST]

# Luego el escaneo automático para lo demás
controllers:
    resource: ../src/Controller/
    type: attribute
