# config/services.yaml
parameters:
    fotos_directory: '%kernel.project_dir%/public/uploads/fotos'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'
